{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "sm-registry.labels" . | nindent 4 }}
  name: {{ include "sm-registry.fullname" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ include "sm-registry.fullname" . }}-tls
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        # rewriteTarget: /$1
        pathType: Prefix
        backend:
          service:
            name: {{ include "sm-registry.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{ end -}}