{{- if (regexMatch ".*:.*" .Values.basicAuth.user) -}}
  {{- fail "Deployment failed: 'basicAuth.user' contains an invalid character ':'" -}}
{{- end -}}

apiVersion: v1
data:
  auth: {{ (htpasswd .Values.basicAuth.user .Values.basicAuth.password) | b64enc | quote }}
kind: Secret
metadata:
  name: faaast-basic-auth-secret
type: Opaque